### ISSUE TITLE
Can't Create Listener + External IP

### ISSUE THREAD

**Issue by bigrittle** [EmpireProject/EmPyre#39]
**EmPyre Version 1.2 (Debian 8 - Python 2.7.9)**

I cannot successfully create a Listener. I am using my external IP address and have tried assigning various ports - whilst running as root the i/o and error are as follows;

set Host http://124.xxx.xx.xxx:443
execute
[!] Error starting listener on IP address 124.xxx.xx.xxx, trying 0.0.0.0 ...

I did read something in the **/Empire** "Impossible for listeners creation" Issue about only internal IP's working when setting up the listener and that External IP's threw errors - Unsure if this is the cause of the issue here/same code in use ?

I really like what I have read/heard of this tool in the Doc's / Bsides talk and am itching to have a play with it ! Hope to be of more use/able to contribute in the future.

Cheers !

**Comment by bneg** [comment]
Did you turn on the --debug flag? I'd recommend turn that on, and pasting in the results here. Is anything else running on :443? I'll typically run a `netstat -antp | grep LISTEN` if I'm unsure

**Comment by bigrittle** [comment]
Bneg, So I ran with the debug flag `python empyre --debug` although the output was the same unless I'm missing something. 

> (EmPyre: listeners) > set Host http://124.xxx.xx.xxx:152
(EmPyre: listeners) > set Port 152
(EmPyre: listeners) > execute 
[!] Error starting listener on IP address 124.xxx.xx.xxx, trying 0.0.0.0 ...
[*] Listener 'test1' successfully started.
(EmPyre: listeners) > 

Also there was nothing running on Port 443 or any other ports I have tried.. Thank you for the `netstat` and `--debug` suggestions though.

**Comment by ch1kpee** [comment]
I'm having this same issue with a Docker container running on DigitalOcean

**Comment by rvrsh3ll** [comment]
Pretty sure you want to create a local listener AND a "foreign" listener. Set the foreign listener to your external IP address. Generate your payloads to the foreign listener.

**Comment by xorrior** [comment]
@bigrittle EmPyre cannot bind to ip addresses that is not available on a local interface. For using an external ip, you will need to use a foreign listener like @rvrsh3ll mentioned.
